server:
  port: 8080

app:
  cors:
    allowed-origins: "http://localhost:5173"

spring:
  application:
    name: api-gateway
  
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /auth

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /users

        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/videos/**, /api/videos
  
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{X-Correlation-ID}]"
