server:
  port: 8080

spring:
  application:
    name: api-gateway

#  cloud:
#    gateway:
#      routes:
#        - id: test-route
#          uri: https://httpbin.org
#          predicates:
#            - Path=/test/**
#      routes:
#        - id: google-route
#          uri: https://www.google.com
#          predicates:
#            - Path=/test/**
#
#        - id: eureka-route
#          uri: http://localhost:8761/hello
#          predicates:
#            - Path=/hello/**
#
#        - id: auth-route
#          uri: http://localhost:8761/hello
#          predicates:
#            - Path=/hello/**
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/videos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  pattern:
    level: "%5p [${spring.application.name:},%X{X-Correlation-ID}]"
